region = "ap-guangzhou"
create_bucket = true
bucket_name = "testbac"
bucket_acl = "private"
multi_az = false
create_bucket_policy = false
log_enable = true
log_prefix = "logPrefix"
#log_target_bucket = ""
versioning_enable = true
cos_file_prefix="cos_file_prefix"